In [144]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [145]:
data=pd.read_csv("iris.data")

In [146]:
X=data.iloc[0:,:-1].values
y=data.iloc[0:,-1].values

In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [148]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [149]:
y_pred = classifier.predict(X_test)

In [150]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14  0  0]
 [ 0 13  1]
 [ 0  1  9]]


0.9473684210526315